version: "3"
services:    
    cloud-ens-cas:
      environment:
        - LDAP_HOST=cloud-ens-opendj
      image: 'osivia/cas:latest'
      depends_on:
        - cloud-ens-opendj
    cloud-ens-es-master:
      command: elasticsearch -Des.cluster.name=demo -Dnetwork.host=0.0.0.0 -Ddiscovery.zen.minimum_master_nodes=1 -Ddiscovery.zen.ping.unicast.hosts=cloud-ens-es-master
      image: 'elasticsearch:1.7.6'
      ports:
        - '9200:9200'
    cloud-ens-httpd:
      environment:
        - CAS_HOST=cloud-ens-cas
        - NUXEO_HOST=cloud-ens-nuxeo
        - 'PORTAL_HOSTS=cloud-ens-portal-1'
        - OO_HOST=onlyoffice        
      image: 'osivia/httpd:certif'
      depends_on:
        - cloud-ens-cas
        - cloud-ens-nuxeo
        - cloud-ens-portal-1
        - onlyoffice
      ports:
        - '80:80'
        - '443:443'
    cloud-ens-mysql:
      command: '--character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci'
      environment:
        - MYSQL_DATABASE=portaldb
        - MYSQL_PASSWORD=osivia
        - MYSQL_ROOT_PASSWORD=osivia
        - MYSQL_USER=portal
      image: 'mysql:5.7'
    cloud-ens-nuxeo:
      environment:
        - 'CAS_HOST=cloud-ens-cas:8080'
        - CAS_PUBLIC_HOST=cloud-ens.osivia.org
        - LDAP_HOST=cloud-ens-opendj
        - NUXEO_DB_HOST=cloud-ens-postgres
        - NUXEO_ES_CLUSTER=demo
        - 'NUXEO_ES_NODES=cloud-ens-es-master:9300'
        - PUBLIC_HOST=cloud-ens.osivia.org
        - OO_HOST=onlyoffice-ip        
      image: 'osivia/cloud-index-ens-nuxeo:dev'
      depends_on:
        - cloud-ens-cas
        - cloud-ens-es-master
        - cloud-ens-opendj
        - cloud-ens-postgres
      ports:
        - "8788:8788"
    cloud-ens-opendj:
      image: 'osivia/opendj:latest'
    cloud-ens-portal-1:
      environment:
        - CAS_HOST=cloud-ens-cas
        - CAS_PUBLIC_HOST=cloud-ens.osivia.org
        - EXTRANET_HOST=cloud-ens-public.osivia.org
        - INTRANET_HOST=cloud-ens.osivia.org
        - LDAP_HOST=cloud-ens-opendj
        - NUXEO_HOST=cloud-ens-nuxeo
        - PORTAL_DB_HOST=cloud-ens-mysql
      image: 'osivia/cloud-index-ens-portal:dev'
      ports:
        - "8787:8787"
      depends_on:
        - cloud-ens-cas
        - cloud-ens-mysql
        - cloud-ens-nuxeo
        - cloud-ens-opendj
    cloud-ens-postgres:
      image: 'osivia/postgres:latest'
    onlyoffice:
      image: onlyoffice/documentserver
      volumes:
        - .\onlyoffice_local.json:/etc/onlyoffice/documentserver/local.json        
      
